name: Deploy (Project Pages)

on:
    push:
        branches: [master]

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
            IS_PRODUCTION: ${{ github.repository == 'eWeLinkCUBE/bridge.sonoff.tech' && 'true' || 'false' }}
            VITE_BASE_URL: ${{ github.repository == 'eWeLinkCUBE/bridge.sonoff.tech' && '/' || '/zigbee-device-table-web-test' }}
            # USE_CUSTOM_DOMAIN: 'true'
            # CUSTOM_DOMAIN: example.com

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Setup Node (LTS) + pnpm cache
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  cache: 'pnpm'
                  cache-dependency-path: pnpm-lock.yaml

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build project
              run: |
                  pnpm build

            - name: Disable Jekyll
              run: touch dist/.nojekyll

            # Create custom path and redirect files only for production deployment
            - name: Create folder for custom path and copy index.html then generate redirect files if production
              if: env.IS_PRODUCTION == 'true'
              run: |
                  mkdir -p dist/device-function-reference-table
                  cp dist/index.html dist/device-function-reference-table/index.html
                  # Create redirect file for custom path
                  echo '<!DOCTYPE html>
                  <html lang="en">
                    <head>
                      <meta charset="UTF-8" />
                      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                      <meta http-equiv="refresh" content="0; url=/device-function-reference-table">
                      <title>Redirecting...</title>
                      <script type="text/javascript">
                        window.location.href = "/device-function-reference-table";
                      </script>
                    </head>
                    <body>
                      <p>If you are not redirected, click <a href="/device-function-reference-table">here</a>.</p>
                    </body>
                  </html>' > dist/index.html

                  # Create 404.html redirect file
                  echo '<!DOCTYPE html>
                  <html lang="en">
                    <head>
                      <meta charset="UTF-8" />
                      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                      <meta http-equiv="refresh" content="0; url=/device-function-reference-table">
                      <title>Redirecting...</title>
                      <script type="text/javascript">
                        window.location.href = "/device-function-reference-table";
                      </script>
                    </head>
                    <body>
                      <p>If you are not redirected, click <a href="/device-function-reference-table">here</a>.</p>
                    </body>
                  </html>' > dist/404.html

            - name: Deploy to gh-pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
